#!perl

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

our %SPEC;

$SPEC{dump_dbi_column_info} = {
    v => 1.1,
    summary => 'Dump DBI column_info() information of a table',
    args => {
        dsn => {
            schema => 'str*',
            req => 1,
            pos => 0,
        },
        table => {
            schema => 'str*',
            req => 1,
            pos => 1,
        },
        user => {
            schema => 'str*',
        },
        password => {
            schema => 'str*',
        },
        catalog => {
            schema => 'str*',
        },
        schema => {
            schema => 'str*',
        },
    },
};
sub dump_dbi_column_info {
    require DBIx::Connect::Any;

    my %args = @_;
    use DD; dd \%args;

    my $dbh = DBIx::Connect::Any->connect(
        $args{dsn}, $args{user}, $args{password},
        {RaiseError=>1});

    my $catalog = $args{catalog} // '';
    my $schema  = $args{schema} // $args{dsn} =~ /\ADBI:SQLite:/ ? 'main' : '';

    my @rows;
    my $sth = $dbh->column_info($catalog, $schema, $args{table}, undef);
    while (my $row = $sth->fetchrow_hashref) {
        push @rows, $row;
    }
    [200, "OK", \@rows];
}

Perinci::CmdLine::Any->new(url => '/main/dump_dbi_column_info')->run;

# ABSTRACT:
# PODNAME:
